#!/bin/bash

password_file=$1
import_vars="/usr/local/lib/etclon3r_lib/vars"

GREEN="\033[0;32m"
RED="\033[0;31m"

# Import variables
source $import_vars

# Mysql database configuration
function Database()
{
	if [ $? -eq 0 ]; then
		echo "[*] Creating new MySQL database..."
		mysql -e "CREATE DATABASE ${dbname} /*\!40100 DEFAULT CHARACTER SET utf8 */;" 2>/dev/null
		if [ $? -eq 0 ]; then
			echo "[*] Database created successfully!"	
		else
			echo "[-] Couldn't create database"
			exit 1
		fi
	else
		echo "[-] Problem occured in database creation"
		exit 1
	fi	

	sleep 1
	if [ $? -eq 0 ]; then
		echo "[*] Creating new MySQL User..."
		mysql -e "CREATE USER ${username}@${dbhost} IDENTIFIED BY '${userpasswd}';" 2>/dev/null
		if [ $? -eq 0 ]; then
			echo "[*] User created successfully!"
		else
			echo "[-] Couldn't create user"
		fi
	else
		echo "[-] Problem occured in user creation"
		exit 1
	fi

	sleep 1
	if [ $? -eq 0 ]; then
		echo "[*] Granting all privileges on ${dbname} to ${username}!"
		mysql -e "GRANT ALL PRIVILEGES ON ${dbname}.* TO '${username}'@'localhost' identified by '${userpasswd}';" 2>/dev/null
		mysql -e "FLUSH PRIVILEGES;" 2>/dev/null
		echo "[*] Privileges setup done!"
	else
		echo "[-] Problem occured with privileges granting"
		exit 1
	fi

	sleep 1
	if [ $? -eq 0 ]; then
		echo "[*] Creating new table called ${tablename}..."
		mysql -e "USE ${dbname}; CREATE TABLE ${tablename}(password1 varchar(30), password2 varchar(30));" 2>/dev/null
		if [ $? -eq 0 ]; then
			echo "[*] Table created successfully!"
			echo "[*] All done"
			echo '**********************************************************'
		else
			echo "[-] Couldn't create table"
		fi
	else
		echo  "[-] Problem occured in tables creation"
		exit 1
	fi

	while true; do		
		wifi_password=$(mysql -e "USE ${dbname}; SELECT * FROM ${tablename};")

		if [ -z "$wifi_password" ]; then
			wifi_password=$(mysql -e "USE ${dbname}; SELECT * FROM ${tablename};")
		else
			data=$(mysql -e "USE ${dbname}; SELECT * FROM ${tablename};")
			password1=$(echo $data | awk '{print $3}')
		    password2=$(echo $data | awk '{print $4}')			
		    if [ $password1 = $password2 ]; then
		    	echo -e "${GREEN}[#] Password is:"
		    	echo -e "${GREEN}[#] $password1" 
		   	else
		    	echo -e "${RED}[#] Passwords are different:"
		    	echo -e "${RED}[#] $password1" 
		    	echo -e "${RED}[#] $password2"
			fi
			sleep 2
			break
		fi

	done
}	

Database
